In [49]:
import numpy as np
from numpy import linalg as LA
from matplotlib import pyplot as plt
import cv2

In [50]:
# Image pixel locations of the corners of the april tags (clock-wise from top-left to bottom-right) (left, right)
x = np.array([
    [284.56243896, 149.29254150],
    [373.93179321, 128.26719666],
    [387.53588867, 220.22708130],
    [281.29962158, 241.72782898],
    [428.86453247, 114.50731659],
    [524.76373291, 92.092185970],
    [568.36596680, 180.55757141],
    [453.60995483, 205.22370911],
])

# World coordinates of the corners of the april tags
X = np.array([
    [0.0000, 0.0000, 1],
    [0.1315, 0.0000, 1],
    [0.1315, 0.1315, 1],
    [0.0000, 0.1315, 1],
    [0.2105, 0.0000, 1],
    [0.3420, 0.0000, 1],
    [0.3420, 0.1315, 1],
    [0.2105, 0.1315, 1],
])



In [51]:
M1 = np.append(np.append(-X,np.zeros(X.shape),axis=1), X*x[:,0,None], axis=1)
M2 = np.append(np.append(np.zeros(X.shape),-X,axis=1), X*x[:,1,None], axis=1)
M  = np.zeros((16,9))

for i in range(8):
    M[2*i,:] = M1[i,:]
    M[2*i+1,:] = M2[i,:]

# SVD of the M Matrix
u, s, vh = LA.svd(M)

# Taking the last row of vh and reshaping it to get the homography matrix
H = vh[-1,:].reshape((3,3))
H = H 
# L = np.matmul(H,np.array([0,0,1]))
# print(L)

In [52]:
print(H)

[[ 6.80736673e-01 -3.91069979e-01  3.13988879e-01]
 [-2.00554997e-01  4.66643122e-01  1.64595846e-01]
 [-1.79175173e-04 -1.29795973e-03  1.10333906e-03]]


In [53]:
lol = np.matmul(H,X.T).T
lol[:,0] = lol[:,0] / lol[:,2]
lol[:,1] = lol[:,1] / lol[:,2]
lol[:,2] = lol[:,2] / lol[:,2]

In [54]:
lol

array([[284.58058999, 149.17975141,   1.        ],
       [373.69341766, 128.01050341,   1.        ],
       [387.28596408, 219.54389283,   1.        ],
       [281.5215864 , 242.27484636,   1.        ],
       [429.12370102, 114.84273121,   1.        ],
       [524.7300731 ,  92.13090561,   1.        ],
       [568.49530203, 180.59825604,   1.        ],
       [453.50280852, 205.31252263,   1.        ]])