In [78]:
import numpy as np
from numpy import linalg as LA
from matplotlib import pyplot as plt
import cv2

In [79]:
# Image pixel locations of the corners of the april tags (clock-wise from top-left to bottom-right) (left, right)
x = np.array([
    [284.56243896, 149.29254150],
    [373.93179321, 128.26719666],
    [387.53588867, 220.22708130],
    [281.29962158, 241.72782898],
    [428.86453247, 114.50731659],
    [524.76373291, 92.092185970],
    [568.36596680, 180.55757141],
    [453.60995483, 205.22370911],
])

# World coordinates of the corners of the april tags
X = np.array([
    [0.0000, 0.0000, 1],
    [0.1315, 0.0000, 1],
    [0.1315, 0.1315, 1],
    [0.0000, 0.1315, 1],
    [0.2105, 0.0000, 1],
    [0.2105, 0.3420, 1],
    [0.1315, 0.3420, 1],
    [0.2105, 0.0000, 1],
])



In [80]:
M1 = np.append(np.append(-X,np.zeros(X.shape),axis=1), X*x[:,0,None], axis=1)
M2 = np.append(np.append(np.zeros(X.shape),-X,axis=1), X*x[:,1,None], axis=1)
M  = np.zeros((16,9))

for i in range(8):
    M[2*i,:] = M1[i,:]
    M[2*i+1,:] = M2[i,:]

# SVD of the M Matrix
u, s, vh = LA.svd(M)

# Taking the last row of vh and reshaping it to get the homography matrix
H = vh[-1,:].reshape((3,3))
# L = np.matmul(H,np.array([0,0,1]))
# print(L)

In [85]:
print(H)

[[-8.98620200e-01  1.80019884e-01  4.39654175e-02]
 [-3.86050497e-01  9.17948327e-02  2.59848690e-02]
 [-2.21406921e-03  4.56632218e-04  1.30887643e-04]]
